USE [master]
GO
/****** Object:  Database [saludDB]    Script Date: 22/09/2024 9:59:26 p. m. ******/
CREATE DATABASE [saludDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'saludDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\saludDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'saludDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\saludDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [saludDB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [saludDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [saludDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [saludDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [saludDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [saludDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [saludDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [saludDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [saludDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [saludDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [saludDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [saludDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [saludDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [saludDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [saludDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [saludDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [saludDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [saludDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [saludDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [saludDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [saludDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [saludDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [saludDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [saludDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [saludDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [saludDB] SET  MULTI_USER 
GO
ALTER DATABASE [saludDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [saludDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [saludDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [saludDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [saludDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [saludDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [saludDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [saludDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [saludDB]
GO
/****** Object:  Table [dbo].[citas]    Script Date: 22/09/2024 9:59:26 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[citas](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[usuario_id] [int] NULL,
	[medico_id] [int] NULL,
	[fecha] [datetime] NULL,
	[estado] [varchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[horarios]    Script Date: 22/09/2024 9:59:26 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[horarios](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[medico_id] [int] NULL,
	[dia_semana] [varchar](10) NULL,
	[hora_inicio] [time](7) NULL,
	[hora_fin] [time](7) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[medicos]    Script Date: 22/09/2024 9:59:26 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[medicos](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[usuario_id] [int] NULL,
	[especialidad] [varchar](100) NULL,
	[nombre] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[usuarios]    Script Date: 22/09/2024 9:59:26 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[usuarios](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](100) NULL,
	[rol] [varchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[citas]  WITH CHECK ADD FOREIGN KEY([medico_id])
REFERENCES [dbo].[medicos] ([id])
GO
ALTER TABLE [dbo].[citas]  WITH CHECK ADD FOREIGN KEY([usuario_id])
REFERENCES [dbo].[usuarios] ([id])
GO
ALTER TABLE [dbo].[horarios]  WITH CHECK ADD FOREIGN KEY([medico_id])
REFERENCES [dbo].[medicos] ([id])
GO
ALTER TABLE [dbo].[medicos]  WITH CHECK ADD FOREIGN KEY([usuario_id])
REFERENCES [dbo].[usuarios] ([id])
GO
USE [master]
GO
ALTER DATABASE [saludDB] SET  READ_WRITE 
GO
